### PR TITLE
Fix 1: Add cursor to icon wrapper and update lower case title to upper case

### PR DESCRIPTION
**Pull request by Rashmi-278**
Summary
- Add cursor to social icon wrapper
- Disable cursor on disabled links
- Add Hover state to social icon wrapper
- Update lower case to upper case titles
- Update error messages

Demo:

https://app.usebubbles.com/vG62Xhjb4kR2TU18h7hxXr/no-cursor-on-disabled-links

### CODE REVIEW

**Comment by Rashmi-278** [comment]
Reverted some changes made in this PR because they were local environment bugs

**Review by kitakaze-kan — APPROVED** [review]
LGFM! Thanks so much!

**Comment by Rashmi-278** [comment]
> LGFM! Thanks so much! Have you already addressed Minamoto's comments in the Vercel preview environment? If so, there should be no problem with merging as is!

Thank you ! Yes, I pushed the commit, Here's the Demo, https://app.usebubbles.com/vG62Xhjb4kR2TU18h7hxXr/no-cursor-on-disabled-links

Please review the PR, It should be good to go

**Comment by KoukiMinamoto** [comment]
Thanks so much, Rashmi-san!
But I meant "no cursor" is `pointer: default`.. sorry for my lack of explanation.
Also, could you eliminate hover state on disable state??

**Comment by Rashmi-278** [comment]
> @Rashmi-278 
> Thanks so much, Rashmi-san!
> But I meant "no cursor" is `pointer: default`.. sorry for my lack of explanation.
> Also, could you eliminate hover state on disable state??
> 

Thank you! Sorry for me not asking, Thank you for clarifying 

I've pushed the changes, please check

**Comment by KoukiMinamoto** [comment]
@Rashmi-278 
Great! Thx!
One more thing, could you eliminate hover state on disable state??

**Comment by Rashmi-278** [comment]
> @Rashmi-278 
> Great! Thx!
> One more thing, could you eliminate hover state on disable state??

Sorry ! My bad, missed that one. 
It should be removed now, please check

**Review by kitakaze-kan — APPROVED** [review]
LGFM! Thanks so much! will merge into Main

**Comment by kitakaze-kan** [comment]
Merged

**Pull request merged**
